// <auto-generated />
namespace GigHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class namechangeofGenrefieldingig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(namechangeofGenrefieldingig));
        
        string IMigrationMetadata.Id
        {
            get { return "201912091326236_name change of Genre field in gig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
